"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Carro_1 = require("./Carro");
const Moto_1 = require("./Moto");
//var carro: Carro = new Veiculo();
var carro = new Carro_1.Carro();
var moto = new Moto_1.Moto();
//var carro: Veiculo = new Carro();
carro.placa = 'Placa carro';
carro.modelo = "Modelo carro";
carro.ano = 1900;
carro.cor = "Vermelho";
console.log(carro);
carro.trocarDeMarcha();
carro.freiar();
carro.virar();
moto.placa = "Placa moto";
moto.modelo = "Modelo moto";
moto.ano = 2000;
moto.cor = "Azul";
console.log(moto);
moto.trocarDeMarcha();
moto.freiar();
